apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-fastapi
  template:
    metadata:
      labels:
        app: devops-fastapi
    spec:
      containers:
        - name: api
          image: devops-fastapi:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

